{
  "version": 3,
  "setup": {
    "blender_install_path": "/home/<env:USER>/blender/",
    "pip": [
      "pyyaml",
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:0>"
        }
      }
    },

    ##### Load shapnet objects and perturbed CC textures with predefined correspondence #####
    {
      "module": "loader.ShapeNetCCMultiLoader",
      "config": {
        "shapenet_path": "<args:1>",
        "cctexture_path": "<args:2>",
        "obj_ids": ["<args:3>"],
        "add_properties": {
          "cp_shape_net_object": True,
        }
      }
    },

    ###### Sample camera poses ######
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
        {
          "number_of_samples": 80,
          "location": {
            "provider":"sampler.Sphere",
            "center": [0, 0, 0],
            "radius": 1,
            "mode": "SURFACE"
          },
          "rotation": {
            "format": "look_at",
            "value": [0, 0, 0],
            "inplane_rot": {
              "provider": "sampler.Value",
              "type": "float",
              "min": -3.14159265359,
              "max": 3.14159265359
            },
          }
        }
        ],
        "intrinsics": {
          "fov": 1.2
        }
      }
    },
    {
      "module": "writer.ObjectStateWriter"
    },
    {
      "module": "writer.LightStateWriter"
    },
    {
      "module": "writer.CameraStateWriter"
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 150,
        "render_distance": True,
        "render_normals": True
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["class", "instance"]
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "append_to_existing_output": True,
        "postprocessing_modules": {
          "distance": [
            {"module": "postprocessing.TrimRedundantChannels"},
            {"module": "postprocessing.Dist2Depth"}
          ]
        }
      }
    }
  ]
}